### ISSUE TITLE
Downloading editor showcase

### ISSUE THREAD

**Issue by ecottis** [SN-RECIT-formation-a-distance/html-bootstrap-editor-showcase#2]
For some reason I am unable to download the files.  Can this be made available, possibly as a zip file so I can host the templates on my own server so users can access our own templates please.

Thanking you for your help

**Comment by emilevirus** [comment]
Hi there,

Thanks for reaching out to us. We use GitHub Actions to generate our showcase and upload it to GitHub Sites. To do this yourself, you can fork the project and then go to your project settings. In the 'Pages' section, configure the name of your page. Once that's done, you can commit a new template and the GitHub page will be generated automatically.
